default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>

development:
  <<: *default
  adapter: postgresql
  encoding: utf8
  database: db_todo
  pool: 5
  host: localhost
  username: postgres
  password: root

test:
  <<: *default
  adapter: postgresql
  encoding: utf8
  database: db_todo
  pool: 5
  host: localhost
  username: postgres
  password: root

production:
  <<: *default
  sadapter: postgresql
  encoding: utf8
  database: somsri_payroll
  pool: 5
  host: localhost
  username: postgres
  password: root
